# Generated by Django 6.0.3 on 2026-03-17 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_notificacion', models.CharField(choices=[('reserva', 'Reserva'), ('partido', 'Partido'), ('postulacion', 'Postulación'), ('sistema', 'Sistema')], max_length=20)),
                ('titulo', models.CharField(max_length=150)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('referencia_id', models.PositiveIntegerField(blank=True, null=True)),
                ('referencia_tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
