# Generated by Django 6.0.3 on 2026-03-17 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('tipo_futbol', models.CharField(choices=[('futbol_5', 'Fútbol 5'), ('futbol_6', 'Fútbol 6'), ('futbol_7', 'Fútbol 7'), ('futbol_11', 'Fútbol 11')], max_length=20)),
                ('capacidad_jugadores', models.PositiveIntegerField()),
                ('ubicacion', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('estado_operativo', models.CharField(choices=[('activa', 'Activa'), ('mantenimiento', 'Mantenimiento'), ('inactiva', 'Inactiva')], default='activa', max_length=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='canchas/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canchas', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Cancha',
                'verbose_name_plural': 'Canchas',
                'ordering': ['empresa__nombre_empresa', 'nombre'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'nombre'), name='unique_nombre_cancha_por_empresa')],
            },
        ),
    ]
