# Generated by Django 6.0.3 on 2026-03-16 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialNivelJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_anterior', models.PositiveSmallIntegerField()),
                ('nivel_nuevo', models.PositiveSmallIntegerField()),
                ('partidos_acumulados', models.PositiveIntegerField(default=0)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_niveles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de nivel del jugador',
                'verbose_name_plural': 'Historial de niveles del jugador',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.CreateModel(
            name='PerfilJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_actual', models.PositiveSmallIntegerField(default=1)),
                ('partidos_confirmados', models.PositiveIntegerField(default=0)),
                ('reputacion', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('activo', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_jugador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de jugador',
                'verbose_name_plural': 'Perfiles de jugador',
            },
        ),
        migrations.CreateModel(
            name='PosicionJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_posicion', models.CharField(choices=[('arquero', 'Arquero'), ('defensa', 'Defensa'), ('medio', 'Medio'), ('delantero', 'Delantero')], max_length=20)),
                ('principal', models.BooleanField(default=False)),
                ('perfil_jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posiciones', to='users.perfiljugador')),
            ],
            options={
                'verbose_name': 'Posición del jugador',
                'verbose_name_plural': 'Posiciones del jugador',
                'constraints': [models.UniqueConstraint(fields=('perfil_jugador', 'nombre_posicion'), name='unique_posicion_por_perfil')],
            },
        ),
    ]
