# Generated by Django 6.0.3 on 2026-03-17 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipos', '0001_initial'),
        ('reservas', '0002_reserva'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_partido', models.CharField(choices=[('publico', 'Público'), ('privado', 'Privado')], max_length=20)),
                ('nivel_partido', models.CharField(choices=[('recreativo', 'Recreativo'), ('intermedio', 'Intermedio'), ('competitivo', 'Competitivo')], default='recreativo', max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('jugadores_faltantes', models.PositiveIntegerField(default=0)),
                ('jugadores_actuales', models.PositiveIntegerField(default=0)),
                ('maximo_jugadores', models.PositiveIntegerField(default=10)),
                ('estado_partido', models.CharField(choices=[('abierto', 'Abierto'), ('completo', 'Completo'), ('en_juego', 'En juego'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='abierto', max_length=20)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateTimeField(blank=True, null=True)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos', to='equipos.equipo')),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partido', to='reservas.reserva')),
                ('usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='PartidoPosicionNecesaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.CharField(choices=[('arquero', 'Arquero'), ('defensa', 'Defensa'), ('medio', 'Medio'), ('delantero', 'Delantero')], max_length=20)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posiciones_necesarias', to='partidos.partido')),
            ],
            options={
                'verbose_name': 'Posición necesaria del partido',
                'verbose_name_plural': 'Posiciones necesarias del partido',
            },
        ),
        migrations.CreateModel(
            name='PostulacionPartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion_postulada', models.CharField(blank=True, choices=[('arquero', 'Arquero'), ('defensa', 'Defensa'), ('medio', 'Medio'), ('delantero', 'Delantero')], max_length=20, null=True)),
                ('nota', models.TextField(blank=True, null=True)),
                ('estado_postulacion', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('fecha_postulacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='partidos.partido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones_partidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Postulación a partido',
                'verbose_name_plural': 'Postulaciones a partidos',
                'ordering': ['-fecha_postulacion'],
                'constraints': [models.UniqueConstraint(fields=('partido', 'usuario'), name='unique_postulacion_por_usuario_y_partido')],
            },
        ),
    ]
