# Generated by Django 6.0.3 on 2026-03-17 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('canchas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=15)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_vigencia_inicio', models.DateField()),
                ('fecha_vigencia_fin', models.DateField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_precio', to='canchas.cancha')),
            ],
            options={
                'verbose_name': 'Configuración de precio',
                'verbose_name_plural': 'Configuraciones de precio',
                'ordering': ['cancha', 'dia_semana', 'hora_inicio'],
                'constraints': [models.UniqueConstraint(fields=('cancha', 'dia_semana', 'hora_inicio', 'hora_fin', 'fecha_vigencia_inicio'), name='unique_config_precio_por_franja')],
            },
        ),
    ]
