# Generated by Django 6.0.3 on 2026-04-04 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='cedula_contacto',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
